# Generated by Django 5.0.3 on 2025-09-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='numero_celular',
            new_name='celular',
        ),
    ]
